name: Security audit
on:
  schedule:
    - cron: '4 0 * * Sat'  # 4:00 each Saturday
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
